### PR TITLE
Troubleshoot/Fix Buffered Reader Closed Stream Bug

### PR DESCRIPTION
**Pull request by ndegwamartin**
- Fix Buffered Reader Closed Stream Bug
- Refactor Permission Checker to handle String type Ids
- Remove invocations of `EntityUtils.toString(entity, "UTF-8");`
- Tix Typo in `LocationHierarchy` endpoint processing

### CODE REVIEW

**Comment by rehammuzzamil** [comment]
Thanks @ndegwamartin .
PR looks good to me, however we need to find a way to parse HttpResponse to relevant FHIR Entities, as mentioned before the use of gson and Jackson libraries were not working.

I will try that again. Thanks.

**Comment by ndegwamartin** [comment]
> Thanks @ndegwamartin . PR looks good to me, however we need to find a way to parse HttpResponse to relevant FHIR Entities, as mentioned before the use of gson and Jackson libraries were not working.
> 
> I will try that again. Thanks.

What were the issues faced with the above two libraries?

**Comment by ndegwamartin** [comment]
@rehammuzzamil I've reinstated the logging for the entity content. We can probably test out the performance implications of this approach

**Comment by ndegwamartin** [comment]
@rehammuzzamil I've reinstated the logging for the entity content. We probably need to test out the performance implications of this approach and its impact to the overall implementation.

**Pull request merged**
